# Doppler secret registry — lazy-loaded, never exported on startup.
# Requires: doppler_get (from functions.sh), load_doppler_cache (already called)
#
# Usage:
#   secret GITHUB_TOKEN                          # one-shot read (no export)
#   GITHUB_TOKEN=$(secret GITHUB_TOKEN) git push # inline for a single command
#   doppler_export GITHUB_TOKEN STRIPE_API_KEY   # export specific vars
#   doppler_export_all                           # export everything (rare)

# zsh-only: associative arrays and typeset -gA are not available in bash
[[ -n "${ZSH_VERSION:-}" ]] || return 0

# Env var name -> doppler key name (only non-identity mappings needed)
typeset -gA _DOPPLER_SECRET_NAMES
_DOPPLER_SECRET_NAMES=(
  [OTEL_INGEST_ROUTE]=OBTOOL_INGEST_ROUTE
  [OTEL_INGEST_URL]=OBTOOL_INGEST_URL
  [OTEL_INGEST_PREVIEW_URL]=OBTOOL_INGEST_PREVIEW_URL
  [OTEL_API_KEY]=OBTOOL_API_KEY
)

# All available secret names (for doppler_export_all and discoverability)
typeset -ga _DOPPLER_ALL_SECRETS
_DOPPLER_ALL_SECRETS=(
  ANTHROPIC_API_KEY
  CLAUDE_API_KEY_ADMIN
  CLAUDE_API_KEY_SUDO
  META_ACCESS_TOKEN
  GOOGLE_ANALYTICS_MEASUREMENT_ID
  GTM_CONTAINER_ID
  GOOGLE_CLIENT_EMAIL
  GOOGLE_PRIVATE_KEY
  GOOGLE_OAUTH_CLIENT_ID_CALENDAR
  GOOGLE_OAUTH_CLIENT_SECRET_CALENDAR
  GOOGLE_TAG_MANAGER_CONTAINER_ID
  RESEND_API_KEY
  LANGTRACE_ACCESS_TOKEN
  LANGTRACE_API_KEY
  OTEL_INGEST_ROUTE
  OTEL_INGEST_URL
  OTEL_INGEST_PREVIEW_URL
  OTEL_API_KEY
  SENTRY_DSN
  SENTRY_AUTH_TOKEN
  SENTRY_API_TOKEN
  SENTRY_TOKEN
  SENTRY_TOKEN_HEADER
  FILE_SYSTEM_SENTRY_DSN
  VITE_SENTRY_DSN
  DOPPLER_DSN
  FB_ANALYTICS_APP_ID
  FB_APP_ID
  FB_APP_SECRET
  FB_PIXEL_ID
  FB_REDIRECT_URI
  GCLOUD_RW_API_KEY
  GEMINI_API_KEY
  GOOGLE_ANALYTICS_API_SECRET
  GMAIL_APP_CLIENT_ID
  GMAIL_APP_SECRET
  GOOGLE_AUTH_CLIENT_SECRET_JSON_2
  GOOGLE_CALENDAR_ACCESS_TOKEN
  GOOGLE_CALENDAR_REFRESH_TOKEN
  GOOGLE_MAPS_API_KEY
  GOOGLE_OAUTH_AUTH_PROVIDER_X509_CERT_URL
  GOOGLE_OAUTH_CLIENT_ID_PERSONAL
  GOOGLE_OAUTH_CLIENT_ID_SCHEDULER
  GOOGLE_OAUTH_CLIENT_SECRET
  GOOGLE_OAUTH_CLIENT_SECRET_PERSONAL
  GOOGLE_OAUTH_CLIENT_SECRET_SCHEDULER
  GOOGLE_OAUTH_PROJECT_ID
  GOOGLE_OAUTH_REDIRECT_URIS
  GOOGLE_OAUTH_TOKEN_URI
  GOOGLE_PUBLIC_KEY
  HUBSPOT_ACCOUNT_ID
  HUBSPOT_DEV_KEY
  HUBSPOT_PAT
  JWT_SECRET
  LINKEDIN_API_KEY
  LINKEDIN_CLIENT_ID
  LINKEDIN_CLIENT_SECRET
  NEXT_PUBLIC_SUPABASE_ANON_KEY
  NEXT_PUBLIC_SUPABASE_URL
  NPM_TOKEN
  CODEX_API_KEY
  OPEN_AI_ADMIN_KEY
  OPEN_AI_KEY
  OPENAI_ACCESS_TOKEN
  OPENAI_API_KEY
  OPENAI_REFRESH_TOKEN
  PLAYWRIGHT_BROWSERS_PATH
  PORKBUN_API_KEY
  PORKBUN_SECRET_API_KEY
  REACT_APP_SUPABASE_ANON_KEY
  REACT_APP_SUPABASE_URL
  REDIS_HOST
  REDIS_PORT
  REDIS_URL
  RENDER_API_KEY
  RENDER_JOBS_API_KEY
  SSH_PUBLIC_KEY_ED25519
  STRIPE_API_KEY
  SUPABASE_ACCESS_TOKEN
  SUPABASE_DB_PASSWORD
  SUPABASE_JWT_SECRET
  SUPABASE_SERVICE_KEY
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_URL
  VITE_ANALYTICSBOT_API_URL
  VITE_ANALYTICSBOT_PROJECT_ID
  VITE_AUTH0_AUDIENCE
  VITE_AUTH0_CLIENT_ID
  VITE_AUTH0_CLIENT_SECRET
  VITE_AUTH0_DOMAIN
  VITE_SUPABASE_ANON_KEY
  VITE_SUPABASE_URL
  TCAD_WORKER_URL
  CLOUDFLARE_ACCOUNT_ID
  CLOUDFLARE_API_TOKEN
  CLOUDFLARE_GLOBAL_API_KEY
  CLOUDFLARE_KV_NAMESPACE_ID
  CLOUDFLARE_OAUTH_TOKEN
  CLOUDFLARE_PAGES_DEPLOY_TOKEN
  CLOUDFLARE_PAGES_GITHUB_TOKEN
  CLOUDFLARE_PAGES_TOKEN
  CLOUDFLARE_REFRESH_TOKEN
  CLOUDFLARE_WORKER_TOKEN
  CLOUDFLARE_ZONE_ID
  DEV_WORKER_URL
  DISCORD_BOT_TOKEN
  DISCORD_CLIENT_ID
  DISCORD_CLIENT_TOKEN
  DISCORD_TOKEN
  COOKIE_SECRET
  GITHUB_TOKEN
)

# Get a secret value without exporting (reads from cache)
# Returns exit code 1 if the secret is empty or missing.
secret() {
  local key="${_DOPPLER_SECRET_NAMES[$1]:-$1}"
  local val
  val="$(doppler_get "$key")"
  if [[ -z "$val" ]]; then
    printf 'secret: %s not found\n' "$1" >&2
    return 1
  fi
  printf '%s' "$val"
}

# Export specific secrets into the environment
doppler_export() {
  local var key
  for var in "$@"; do
    key="${_DOPPLER_SECRET_NAMES[$var]:-$var}"
    export "$var"="$(doppler_get "$key")"
  done
}

# Export all registered secrets (backward-compat escape hatch)
doppler_export_all() {
  doppler_export "${_DOPPLER_ALL_SECRETS[@]}"
}
