# Bash profile

# Load bashrc if it exists
[[ -f ~/.bashrc ]] && source ~/.bashrc

# macOS specific: Add Homebrew to PATH
if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
# macOS specific: use pyenv python version manager
export PYENV_ROOT="$HOME/.pyenv
[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
